In [2]:
import tensorflow as tf
import matplotlib
import numpy as np


In [3]:
tf.__version__

'2.18.0'

In [4]:
constant_tf=tf.constant([[1,2],[3,4]])

In [5]:
constant_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
variable_tf=tf.Variable([[5,6],[1,3]])

In [ ]:
variable_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [1, 3]], dtype=int32)>

In [ ]:
transpose_tf=tf.transpose(constant_tf)

In [ ]:
transpose_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [ ]:
multipl_mat=tf.multiply(constant_tf,transpose_tf)

In [ ]:
multipl_mat2=tf.matmul(constant_tf,transpose_tf)

In [ ]:
multipl_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [ 6, 16]], dtype=int32)>

In [ ]:
multipl_mat2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 11],
       [11, 25]], dtype=int32)>

In [ ]:
tensor_transpose_float=tf.cast(multipl_mat2,tf.float32)

In [ ]:
determinant=tf.linalg.det(tensor_transpose_float)

In [ ]:
inver=tf.linalg.inv(tensor_transpose_float)

In [ ]:
inver

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.24999  , -2.7499955],
       [-2.7499955,  1.249998 ]], dtype=float32)>

In [ ]:
ZERO_TSR=tf.zeros(shape=[2,3],dtype=tf.int32)

In [ ]:
ZERO_TSR

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
ONES_TSR=tf.ones(shape=[2,3],dtype=tf.float32)

In [ ]:
ONES_TSR

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np

In [ ]:
Iris_Data=np.array([[1,2,3,4],[2,1,5,4]])

In [ ]:
Iris_Data

array([[1, 2, 3, 4],
       [2, 1, 5, 4]])

In [ ]:
TSR_iris=tf.convert_to_tensor(Iris_Data)

In [ ]:
Iris_Data

array([[1, 2, 3, 4],
       [2, 1, 5, 4]])

In [ ]:
TSR_iris

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [2, 1, 5, 4]])>