In [30]:
import tensorflow as tf
import matplotlib
import numpy as np


In [31]:
tf.__version__

'2.18.0'

In [32]:
constant_tf=tf.constant([[1,2],[3,4]])

In [33]:
constant_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [34]:
variable_tf=tf.Variable([[5,6],[1,3]])

In [35]:
variable_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [1, 3]], dtype=int32)>

In [36]:
transpose_tf=tf.transpose(constant_tf)

In [37]:
transpose_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [38]:
multipl_mat=tf.multiply(constant_tf,transpose_tf)

In [39]:
multipl_mat2=tf.matmul(constant_tf,transpose_tf)

In [40]:
multipl_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [ 6, 16]], dtype=int32)>

In [41]:
multipl_mat2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 11],
       [11, 25]], dtype=int32)>

In [42]:
tensor_transpose_float=tf.cast(multipl_mat2,tf.float32)

In [43]:
determinant=tf.linalg.det(tensor_transpose_float)

In [44]:
inver=tf.linalg.inv(tensor_transpose_float)

In [45]:
inver

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.24999  , -2.7499955],
       [-2.7499955,  1.249998 ]], dtype=float32)>

In [46]:
ZERO_TSR=tf.zeros(shape=[2,3],dtype=tf.int32)

In [47]:
ZERO_TSR

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [48]:
ONES_TSR=tf.ones(shape=[2,3],dtype=tf.float32)

In [49]:
ONES_TSR

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [50]:
import numpy as np

In [51]:
Iris_Data=np.array([[1,2,3,4],[2,1,5,4]])

In [52]:
Iris_Data

array([[1, 2, 3, 4],
       [2, 1, 5, 4]])

In [53]:
TSR_iris=tf.convert_to_tensor(Iris_Data)

In [54]:
Iris_Data

array([[1, 2, 3, 4],
       [2, 1, 5, 4]])

In [55]:
TSR_iris

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [2, 1, 5, 4]])>